/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./components/my-dialog1 copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MyDialog: typeof import('./components/my-dialog.vue')['default']
    MyDialog1: typeof import('./components/my-dialog1.vue')['default']
    MyDialog2: typeof import('./components/my-dialog2.vue')['default']
    MyPopup: typeof import('./components/popup/my-popup.vue')['default']
  }
}
